services:
  node:
    build:
      context: .
      dockerfile: ./docker/containers/node/Dockerfile
      target: base
    volumes:
      - ./node/src:/home/node/app/src
      - ./node/nodemon.json:/home/node/app/nodemon.json
      - ./node/tsconfig.json:/home/node/app/tsconfig.json
      - ./node/.env:/home/node/app/.env
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev

  db:
    build:
      context: .
      dockerfile: ./docker/containers/postgres/Dockerfile
      target: base
    volumes:
      - ./docker/containers/postgres/sayari.sql:/docker-entrypoint-initdb.d/sayari.sql
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sayari
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -P password -d sayari'"]
      interval: 1s
      timeout: 5s
      retries: 10
    expose:
      - '5432'
    ports:
      - '5432:5432'
      
  redis:
    build:
      context: .
      dockerfile: ./docker/containers/redis/Dockerfile
      target: base
    volumes:
      - ./docker/containers/redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - '6379'
    ports:
      - '6379:6379'
